#!/usr/bin/with-contenv sh

# Delete useless repo dir
if [ -d $WODBY_HOME/repo ]; then
    rm -rf $WODBY_HOME/repo
fi

# Put env vars into /var/run/wodby/env
if [ ! -d /var/run/wodby ]; then
    mkdir -p /var/run/wodby
    chown $WODBY_USER:$WODBY_GROUP /var/run/wodby
fi

# Filter env vars and store
printenv | xargs -I{} echo {} | awk ' \
    BEGIN { FS = "=" }; { \
        if ($1 != "HOME" \
            && $1 != "PWD" \
            && $1 != "PATH" \
            && $1 != "SHLVL" \
            && $1 != "S6_LOGGING" \
            && $1 != "S6_LOGGING_SCRIPT") { \
            \
            print ""$1"="$2"" \
        } \
    }' > /var/run/wodby/env

chown $WODBY_USER:$WODBY_GROUP /var/run/wodby/env

# Ensure needed dirs, files, permissions
chown $WODBY_USER:$WODBY_GROUP $WODBY_HOME

if [ ! -d $WODBY_CONF ]; then
    mkdir $WODBY_HOME/.ssh
    chown $WODBY_USER:$WODBY_GROUP $WODBY_HOME/.ssh
    chmod 700 $WODBY_HOME/.ssh
fi

# Generate env vars for sh profile
cat /var/run/wodby/env | xargs -I{} echo {} | awk 'BEGIN { FS = "=" }; { print "export "$1"="$2"" }' > /var/run/wodby/profile-env
chown $WODBY_USER:$WODBY_GROUP /var/run/wodby/profile-env
chmod +x /var/run/wodby/profile-env

# Delete old style .profile
if [ -f $WODBY_HOME/.profile ] && [ $( grep -ic "/var/run/wodby/profile-env" $WODBY_HOME/.profile ) -eq 0 ]; then
    rm $WODBY_HOME/.profile
fi

# Create .profile
if [ ! -f $WODBY_HOME/.profile ]; then
    # Generate .profile
    echo -e 'alias ls="ls --color"' >> $WODBY_HOME/.profile
    echo -e 'alias ll="ls -lah --color"' >> $WODBY_HOME/.profile
    echo -e '. /var/run/wodby/profile-env' >> $WODBY_HOME/.profile
    chown $WODBY_USER:$WODBY_GROUP $WODBY_HOME/.profile
fi

if [ ! -d $WODBY_CONF ]; then
    mkdir $WODBY_CONF
    chown $WODBY_USER:$WODBY_GROUP $WODBY_CONF
fi

if [ ! -d $WODBY_LOGS ]; then
    mkdir $WODBY_LOGS
    chown $WODBY_USER:$WODBY_GROUP $WODBY_LOGS
fi

if [ ! -d $WODBY_FILES ]; then
    mkdir $WODBY_FILES
    mkdir $WODBY_FILES/public
    mkdir $WODBY_FILES/private
    chown -R $WODBY_USER:$WODBY_GROUP $WODBY_FILES
fi

# Do not create backup directory, because it mounted from the host machine
if [ -d $WODBY_BACKUPS ]; then
    chown $WODBY_USER:$WODBY_GROUP $WODBY_BACKUPS
fi

if [ ! -d $WODBY_HOME/.wodby/locks ]; then
    mkdir -p $WODBY_HOME/.wodby/locks
    chown -R $WODBY_USER:$WODBY_GROUP $WODBY_HOME/.wodby
fi

# Replace env vars in confd templates
sed -i -e 's@${WODBY_NAMESPACE}@'"${WODBY_NAMESPACE}"'@' /etc/confd/conf.d/*.toml
sed -i -e 's@${WODBY_USER}@'"${WODBY_USER}"'@' /etc/confd/conf.d/*.toml
sed -i -e 's@${WODBY_GUID}@'"${WODBY_GUID}"'@' /etc/confd/conf.d/*.toml
sed -i -e 's@${WODBY_CONF}@'"${WODBY_CONF}"'@' /etc/confd/conf.d/*.toml
sed -i -e 's@${WODBY_APP_TYPE}@'"${WODBY_APP_TYPE}"'@' /etc/confd/conf.d/*.toml
sed -i -e 's@${WODBY_APP_VERSION}@'"${WODBY_APP_VERSION}"'@' /etc/confd/conf.d/*.toml
