#!/usr/bin/with-contenv sh

if [ "${WODBY_ENVIRONMENT_TYPE}" = "dev" ]; then
    sed -i "s/^error_reporting.*/error_reporting = E_ALL/" /etc/php/php.ini
    sed -i "s/^display_errors.*/display_errors = On/" /etc/php/php.ini
    sed -i "s/^display_startup_errors.*/display_startup_errors = On/" /etc/php/php.ini
    sed -i "s/^track_errors.*/track_errors = On/" /etc/php/php.ini
    sed -i "s/^mysqlnd.collect_memory_statistics.*/mysqlnd.collect_memory_statistics = On/" /etc/php/php.ini
fi

echo -e "\n;;;;;;;;;;;;;;;;;;;;;;;;;\n; Environment variables ;\n;;;;;;;;;;;;;;;;;;;;;;;;;\n" >> /etc/php/php-fpm.conf && \
    printenv | xargs -I{} echo {} | awk 'BEGIN { FS = "=" }; { print "env["$1"] = "$2 }' >> /etc/php/php-fpm.conf && \
    echo -e "\n"
